In [10]:
import pandas as pd 
import numpy as np
import logging 

logging.basicConfig(
    level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s',
    filename='quant.log'
)
logger = logging.getLogger(__name__)

In [11]:
# loading data 
df = pd.read_csv('cleaned_credit_risk_dataset.csv')
logger.info('Data loaded successfully')
df

,age,income,emp_length,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,default_on_file,cred_hist_length,home_ownership_MORTGAGE,home_ownership_OTHER,home_ownership_OWN,home_ownership_RENT,loan_intent_DEBTCONSOLIDATION,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE
0,22,59000,123.0,4,35000,16.02,1,0.59,1,3,0,0,0,1,0,0,0,0,1,0
1,21,9600,5.0,2,1000,11.14,0,0.10,0,2,0,0,1,0,0,1,0,0,0,0
2,25,9600,1.0,3,5500,12.87,1,0.57,0,3,1,0,0,0,0,0,0,1,0,0
3,23,65500,4.0,3,35000,15.23,1,0.53,0,2,0,0,0,1,0,0,0,1,0,0
4,24,54400,8.0,3,35000,14.27,1,0.55,1,4,0,0,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28490,31,83000,9.0,6,18000,19.74,1,0.22,1,8,1,0,0,0,0,0,0,0,0,1
28491,29,61656,4.0,1,15000,6.91,0,0.24,0,9,0,0,0,1,0,0,0,0,1,0
28492,32,30000,1.0,2,11450,9.99,1,0.38,0,6,0,0,0,1,0,1,0,0,0,0
28493,31,26010,2.0,2,6500,9.99,0,0.25,0,9,1,0,0,0,0,0,0,0,1,0
28494,30,52000,4.0,2,14675,9.63,0,0.28,0,7,1,0,0,0,0,0,1,0,0,0

In [12]:
# select numerical features 
num_cols = ['age', 'income', 'emp_length', 'loan_grade', 'loan_amnt', 'loan_int_rate', 'loan_status', 'loan_percent_income', 'default_on_file', 'cred_hist_length']

# initialize results list 
results = []

# for each column 
for col in num_cols:
    # drop missing values
    data = df[col].dropna()
    
    n = len(data)
    mean = data.mean()
    std = data.std(ddof=1)
    
    # standard error
    se = std / np.sqrt(n)
    
    # 95% confidence interval 
    ci_lower = mean - 1.96 * se
    ci_upper = mean + 1.96 * se
    
    results.append({
        "feature": col,
        "mean": round(mean, 2),
        "std_dev": round(std, 2),
        "standard_error": round(se, 2),
        "ci_lower_95": round(ci_lower, 2),
        "ci_upper_95": round(ci_upper, 2)
    })
    logger.info(f'Results for {col} added to results list.')

ci_df = pd.DataFrame(results)
logger.info('Printing ci results dataframe.')
ci_df

,feature,mean,std_dev,standard_error,ci_lower_95,ci_upper_95
0,age,25.89,3.44,0.02,25.85,25.93
1,income,64149.33,41883.03,248.12,63663.02,64635.63
2,emp_length,4.61,3.76,0.02,4.57,4.65
3,loan_grade,2.21,1.16,0.01,2.20,2.22
4,loan_amnt,9536.37,6271.80,37.15,9463.55,9609.19
5,loan_int_rate,10.99,3.08,0.02,10.96,11.03
6,loan_status,0.22,0.41,0.00,0.21,0.22
7,loan_percent_income,0.17,0.11,0.00,0.17,0.17
8,default_on_file,0.18,0.38,0.00,0.17,0.18
9,cred_hist_length,4.68,2.50,0.01,4.65,4.71